[[redirects]]
    from = "https://cat.jnsst.com.br/*"
    to = "https://www.jnsst.com.br/cat"
    status = 200
    force = true


[[redirects]]
    from = "https://cat.jnsst.com.br/*"
    to = "https://www.jnsst.com.br/cat"
    status = 200
    force = true