const exams = [
  "Audiometria", 
  "Avaliação Psicossocial", 
  "Avaliação de Acuidade Visual", 
  "Brucelose Teste Rápido", 
  "Chumbo Urinário", 
  "Coprocultura de Fezes", 
  "Coproparasitológico de Fezes", 
  "Creatina", 
  "Eletrocardiograma (ECG)", 
  "Eletroencefalograma (EEG)", 
  "Espirometria", 
  "Gama GT", 
  "Glicemia", 
  "Hemograma Completo", 
  "Raio - X Coluna Lombo-Sacra", 
  "Raio - X Tórax Padrão OIT", 
  "Reticulócitos", 
  "Sorologia para Brucelose", 
  "Sumário de Urina (EAS)", 
  "Sífilis (VDRL)", 
  "TGO", 
  "TGP", 
  "Teste de Romberg", 
  "Tipagem Sanguínea", 
  "Triglicerídeos", 
  "Uréia"
];

export default exams;